title: Allyson da Silva
baseURL: https://whataboutdata.netlify.app/
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Home
    weight: 1
  fr:
    contentDir: content/fr
    title: Accueil
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  author: ''
  background_color_class: bg-black
  description: 
  facebook: ''
  favicon: ''
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  github: 'https://github.com/AllysonAOdS'
  gitlab: ''
  instagram: ''
  linkedin: 'https://www.linkedin.com/in/allyson-silva-95aa3a22/?locale=en_US'
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: 
  youtube: ''
  xing: 'https://www.xing.com/profile/Allyson_daSilva/cv'
